### ISSUE TITLE
Change from GPL ver. 3 to BSD or MIT ?

### ISSUE THREAD

**Issue by snakefoot** [farzadpanahi/NLog.GelfLayout#23]
I know that NLog.GelfLayout was inspired by [Gelf4NLog](https://github.com/seymen/Gelf4NLog) that is GPL ver. 3

But the [GelfConverter.cs](https://github.com/farzadpanahi/NLog.GelfLayout/blame/master/src/NLog.Layouts.GelfLayout/GelfConverter.cs) is now a complete rewrite by me, so there is no code-sharing or code-reuse anymore.

@tomikiss + @farzadpanahi Would you have any issues with changing the license from GPL ver. 3 to BSD-License or MIT-License ? (Have my permission to do it)

**Comment by farzadpanahi** [comment]
But which part of GPL3 you don't like? The part that code cannot be used in closed source?

**Comment by snakefoot** [comment]
> But which part of GPL3 you don't like?

That only in-house applications can use this nuget-package. Else they have to opensource their entire application.

**Comment by farzadpanahi** [comment]
Fair enough. Change it.

**Comment by snakefoot** [comment]
Sorry for the noise. Can see the license is "GNU **LESSER** GENERAL PUBLIC LICENSE" so it is perfect as it is.

So anyone who make forks of this repository, are required to keep their fork open-source. But the application using the fork can remain closed source.
