### ISSUE TITLE
Can't add extra fields like a example in readme

### ISSUE THREAD

**Issue by joaopalma5** [farzadpanahi/NLog.GelfLayout#24]
Hello,

In my project if i make this ( https://github.com/farzadpanahi/NLog.GelfLayout#sample-usage-with-custom-extra-fields ) example without extra fields, the Gelf Log works good!
But if I add extra fields, like this example ( https://github.com/farzadpanahi/NLog.GelfLayout#sample-usage-with-custom-extra-fields ), the program sends an error in runtime "Layout cannot be found: 'GelfLayout'"

Error details:
NLog.NLogConfigurationException
  HResult=0x80131500
  Message=Exception when parsing 
(...)
ArgumentException: Layout cannot be found: 'GelfLayout'

**Comment by snakefoot** [comment]
Remember to include this (part of the example):
```xml
  <extensions>
    <add assembly="NLog.Layouts.GelfLayout" />
  </extensions>
```
And make sure to use lastest version of the [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout) nuget-package:

Else please attach a simple example-project that reproduces the issue.
