### ISSUE TITLE
Re-add owner on nuget.org

### ISSUE THREAD

**Issue by tomikiss** [farzadpanahi/NLog.GelfLayout#26]
Hi @farzadpanahi ,

Would you able to add my nuget.org user (tomikiss87) as a package owner to cut a new release? Thanks for your help.

**Comment by tomikiss** [comment]
Hi @farzadpanahi , it seems like I still have issue on nuget.org , would you able to retry it? I don't seems the user tomikiss87 as an owner so not able to push a new version. Thanks again for your help.

**Comment by farzadpanahi** [comment]
Sorry. I thought you want access to github repo. I checked my nuget account and apparently they have disabled nuget.org username/password logins. I need to contact them to see how I can retrieve my account using MS login.

**Comment by farzadpanahi** [comment]
Should work now.
