### ISSUE TITLE
When specifying a field with the name source and layout different from the lowercase word, udp gelf does not work

### ISSUE THREAD

**Issue by UseMuse** [farzadpanahi/NLog.GelfLayout#30]
When specifying a field with the name source and layout different from the lowercase word, udp gelf does not work
This is how it works

``` xml
<field name="source" layout="producersrequestswebapicore" />
```
or
``` xml
<field name="source" layout="producers-requests-web-api-core" />
```
or
``` xml
<field name="source" layout="producers_requests_web_api_core" />
```
But no
``` xml
<field name="source" layout="producersRequestsWebApiCore" />
```
or
``` xml
<field name="source" layout="ProducersRequestsWebApiCore" />
```

asp core 3.1 web api 
NLog.GelfLayout 1.4.0

....probably because source is used in index in elk

**Comment by snakefoot** [comment]
NLog supports`${message:lowercase=true}`, so you can just add `lowercase=true`-option to the Layout, and output will become lowercase.

**Comment by UseMuse** [comment]
existing limitation
must not contain the characters #, \, /, *, ?, ", <, >, |, ,
Since ES 7.0 onwards, : is not allowed as well
must not start with _, - or +
must not be. or ..
must be lowercase
@snakefoot yes, I think this will work, thanks
