### ISSUE TITLE
Truncated messages

### ISSUE THREAD

**Issue by UseMuse** [farzadpanahi/NLog.GelfLayout#34]
Can make message length FullMessageMaxLength and ShortMessageMaxLength configurable?
not hardcoded

**Comment by snakefoot** [comment]
Not sure what is meant by configurable but not hardcoded. But you can override `fullMessage` + `shortMessage`:
```xml
	<target xsi:type="Network" name="GelfHttp" address="http://localhost:12201/gelf">
		<layout type="GelfLayout" fullMessage="${message:truncate=128}" shortMessage="${message:truncate=128}">
                </layout>
	</target>
```
Introduced with [NLog.GelfLayout](https://www.nuget.org/packages/NLog.GelfLayout) ver.  1.5.0

**Comment by UseMuse** [comment]
@snakefoot [GelfConverter.cs](https://github.com/farzadpanahi/NLog.GelfLayout/blob/master/src/NLog.Layouts.GelfLayout/GelfConverter.cs)
fields FullMessageMaxLength 

when I send data to elk, the data is cut off due to the limitation of the FullMessageMaxLength field, which leads the data to invalid json, thus in elk it falls with an error and does not end up in the log

**Comment by snakefoot** [comment]
I guess if the GELF-spec has changed, then the hardcoded max-lengths should be updated.

Sounds strange with "invalid json" from truncating a message. Unless you are trying to send pure json as the LogEvent-message.

It sounds like an exotic scenario, but I guess pull-requests are wellcome, then the repo-maintainer can make a decision.

**Comment by UseMuse** [comment]
@snakefoot  Please advise how to configure Nlog udp so that when sending data of a size larger than 8192, the message is not truncated but is delivered in full?

My config

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	<extensions>
		<add assembly="NLog.Layouts.GelfLayout" />
	</extensions>
	<targets async="true">
		<target xsi:type="Network" name="gelfUdpRequestResponse" address="udp://my:12201">
			<layout type="GelfLayout">
				<field name="lang" layout="dotnet" />
				<field name="source" layout="${moduleNameForGelfSource}" />
				<field name="facility" layout="${aspnet-environment}" />
				<field name="UserName" layout="${username}"/>
			</layout>
		</target>
	</targets>

	<rules>
		<logger name="requestResponseDbLog" minlevel="Info" writeTo="gelfUdpRequestResponse" />
	</rules>
</nlog>
```

```c#
                LogHelper.RequestResponseLogger.WithProperty("Host", host)
                          .WithProperty("Request", requestStr)
                          .WithProperty("RequestBody", requestBodyStr)
                          .WithProperty("Response", responseStr)
                          .WithProperty("ResponseBody", responseBodyStr)
                          .Info("RequestResponse Info");
```

**Comment by UseMuse** [comment]
Does not help 
```
<target xsi:type="Network" name="gelfUdpRequestResponse" address="udp://my:12201" maxQueueSize="10000" onOverflow="Split" maxMessageSize="900000">  
```

**Comment by UseMuse** [comment]
@snakefoot to make a contribution you will have to create a class derived from TargetWithLayout in order to implement your own udp Transport in it, I could try to do this, another question, will you accept such a contribution? maybe this can be implemented differently, I don’t know how else

**Comment by UseMuse** [comment]
https://github.com/NLog/NLog.Targets.Network/issues/2

**Comment by snakefoot** [comment]
Maybe consider creating a pull-request for this repo, that introduces a new project called NLog.GelfUdpTarget and copy the logic from here:

https://github.com/seymen/Gelf4NLog/blob/master/Target/UdpTransport.cs

And using NLog.GelfLayout as Target-Layout. See also: https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

**Comment by UseMuse** [comment]
@snakefoot Thank you, I would like to be able to influence this behavior

```c#
//https://github.com/farzadpanahi/NLog.GelfLayout/blob/master/src/NLog.Layouts.GelfLayout/GelfConverter.cs
  case TypeCode.String:
                    var propertyString = propertyValue.ToString();
                    if (propertyString.Length > FullMessageMaxLength)
                    {
                        propertyString = propertyString.Substring(0, FullMessageMaxLength);
                    }

```

**Comment by snakefoot** [comment]
Sounds like you have lots of ideas for creating different pull-requests.

**Comment by snakefoot** [comment]
Created NLog/NLog#35 that tries to improve documentation about UDP.
